FROM debian:stable-slim as builder
RUN set -ex \
  && DEBIAN_FRONTEND=noninteractive apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --no-install-recommends --no-install-suggests \
	ca-certificates \
	curl \
	git \
	unzip

ARG TERRAFORM_VERSION
RUN set -ex \
  && curl -sSL https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip --output terraform.zip \
  && unzip terraform.zip \
  && mv terraform /usr/bin/terraform \
  && chmod +x /usr/bin/terraform

ARG TERRAGRUNT_VERSION
RUN set -ex \
  && curl -sSL https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 --output /usr/bin/terragrunt \
  && chmod +x /usr/bin/terragrunt

FROM python:slim-buster
LABEL maintainer="nilsas@firantas.lt"
ARG AGENT_VERSION
COPY --from=builder /usr/bin/terraform /usr/bin/terraform
COPY --from=builder /usr/bin/terragrunt /usr/bin/terragrunt
WORKDIR /agent
RUN adduser --disabled-password --uid 1234 --gecos "" agent
RUN set -ex \
  && apt-get update \
  && apt-get install -qq -y --no-install-recommends --no-install-suggests git curl \
  && curl -sSL https://vstsagentpackage.azureedge.net/agent/$AGENT_VERSION/vsts-agent-linux-x64-$AGENT_VERSION.tar.gz --output vsts-agent-linux-x64-$AGENT_VERSION.tar.gz \
  && tar xzf vsts-agent-linux-x64-$AGENT_VERSION.tar.gz \
  && rm -f vsts-agent-linux-x64-$AGENT_VERSION.tar.gz \
  && ./bin/installdependencies.sh \
  && chown -R agent:agent /agent \  
  && apt-get autoremove -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER agent
ENTRYPOINT ["/bin/bash", "-c", "./config.sh --unattended --url $AZDO_URL --auth pat --token $AZDO_TOKEN --pool $AZDO_POOL --agent $AZDO_AGENT_NAME --acceptTeeEula --replace && unset AZDO_TOKEN && ./run.sh"]